# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy manifest files
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project
RUN npm run build

# Ensure the CLI is executable
RUN chmod +x build/index.js

# Default command to run the MCP server
CMD ["node", "build/index.js"]
